# Netlify deployment configuration
[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/simple-deployment-server.js"
  status = 200
