services:
  - type: web
    name: crypto-monitor
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEBSOCKET_PORT
        value: 10001
